# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tp < Formula
  desc "A terminal-based application that displays the result of commands at every keystroke."
  homepage "https://github.com/minefuto/tp"
  version "2.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/minefuto/tp/releases/download/v2.0.0/tp_2.0.0_darwin_amd64.tar.gz"
      sha256 "3a87c70c3c853c0aa7f8cd1e804f3e8fb62ad2d8710c7d30be3698b8f23b2ac1"

      define_method(:install) do
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/minefuto/tp/releases/download/v2.0.0/tp_2.0.0_darwin_arm64.tar.gz"
      sha256 "77f39e2c5aed70bcdde17348deaf6c3820e0371305e386b77f9cfb99ef08d832"

      define_method(:install) do
        bin.install "tp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/minefuto/tp/releases/download/v2.0.0/tp_2.0.0_linux_amd64.tar.gz"
      sha256 "58216ba3dc9a512068a11aa584b024f2c16dbbea1d8e28308d8c074f03fc7e73"
      define_method(:install) do
        bin.install "tp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/minefuto/tp/releases/download/v2.0.0/tp_2.0.0_linux_arm64.tar.gz"
      sha256 "56af41f8ded64a14717fef20a7dd7d8116bd30639c3f7cb67be3e8cef8dca7cd"
      define_method(:install) do
        bin.install "tp"
      end
    end
  end
end
